### ISSUE TITLE
'polyline_ggl/decode' is not a valid module name

### ISSUE THREAD

**Issue by gson1703** [mthh/polyline_ggl#1]
Hi,

Trying to install the module with Python 2.7, I get the following error:

```
$ python2.7 setup.py install
Compiling polyline_ggl/decode.pyx because it changed.
Compiling polyline_ggl/encode.pyx because it changed.
[1/2] Cythonizing polyline_ggl/decode.pyx

Error compiling Cython file:
------------------------------------------------------------
...
# -*- coding: utf-8 -*-
^
------------------------------------------------------------

polyline_ggl/decode.pyx:1:0: 'polyline_ggl/decode' is not a valid module name
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    ext_modules=cythonize(exts),
  File "/usr/pkg/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/usr/pkg/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: polyline_ggl/decode.pyx
```

**Comment by mthh** [comment]
Hi,

Thanks for the report ! I changed how the extensions are imported in my last commit (5b06954) and it seems to work on both python 2.7 and 3.x. Don't hesitate to tell me if it still does not work for you.

**Comment by gson1703** [comment]
It works fine now, thank you for the quick response!
